services:
  postgres:
    hostname: potgres
    image: ankane/pgvector
    ports:
     - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - .:/app
volumes:
  pgdata:
