services:
  postgres:
    hostname: potgres
    image: ankane/pgvector
    ports:
     - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    container_name: web_app
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
  integration:
    container_name: tests
    build:
      context: .
      dockerfile: Dockerfile
      target: tests
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres
volumes:
  pgdata:
